/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFeedbackModal: typeof import('./src/components/feedback/AppFeedbackModal.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppMobileNavigation: typeof import('./src/components/layout/AppMobileNavigation.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    BackgroundTaskToastHost: typeof import('./src/components/layout/BackgroundTaskToastHost.vue')['default']
    ChatConversationHistoryPanel: typeof import('./src/components/chat/ChatConversationHistoryPanel.vue')['default']
    ChatDateTimePicker: typeof import('./src/components/chat/ChatDateTimePicker.vue')['default']
    ChatMarkdownContent: typeof import('./src/components/chat/ChatMarkdownContent.vue')['default']
    CityPicker: typeof import('./src/components/CityPicker.vue')['default']
    GlobalChatAssistant: typeof import('./src/components/chat/GlobalChatAssistant.vue')['default']
    GlobalChatAssistantShell: typeof import('./src/components/chat/GlobalChatAssistantShell.vue')['default']
    InterviewScheduleConfirmationCard: typeof import('./src/components/chat/InterviewScheduleConfirmationCard.vue')['default']
    InterviewScheduleInputCard: typeof import('./src/components/chat/InterviewScheduleInputCard.vue')['default']
    MockInterviewConfirmationCard: typeof import('./src/components/chat/MockInterviewConfirmationCard.vue')['default']
    MockInterviewInputCard: typeof import('./src/components/chat/MockInterviewInputCard.vue')['default']
    OpportunityImportResultCard: typeof import('./src/components/chat/OpportunityImportResultCard.vue')['default']
    OpportunityIntentionConfirmationCard: typeof import('./src/components/chat/OpportunityIntentionConfirmationCard.vue')['default']
    OpportunityMutationSummaryCard: typeof import('./src/components/chat/OpportunityMutationSummaryCard.vue')['default']
    OpportunityProfileBatchConfirmationCard: typeof import('./src/components/chat/OpportunityProfileBatchConfirmationCard.vue')['default']
    OpportunityProfileConfirmationCard: typeof import('./src/components/chat/OpportunityProfileConfirmationCard.vue')['default']
    OpportunityReferencePicker: typeof import('./src/components/chat/OpportunityReferencePicker.vue')['default']
    OpportunitySearchResultCard: typeof import('./src/components/chat/OpportunitySearchResultCard.vue')['default']
    OpportunitySearchResultSkeleton: typeof import('./src/components/chat/OpportunitySearchResultSkeleton.vue')['default']
    OpportunityStatusTransitionConfirmationCard: typeof import('./src/components/chat/OpportunityStatusTransitionConfirmationCard.vue')['default']
    OpportunityTargetInputCard: typeof import('./src/components/chat/OpportunityTargetInputCard.vue')['default']
    OpportunityTerminationCard: typeof import('./src/components/chat/OpportunityTerminationCard.vue')['default']
    ResumeTargetInputCard: typeof import('./src/components/chat/ResumeTargetInputCard.vue')['default']
    ReviewConfirmationCard: typeof import('./src/components/chat/ReviewConfirmationCard.vue')['default']
    ReviewInputCard: typeof import('./src/components/chat/ReviewInputCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCalendar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UChatMessages: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/ChatMessages.vue')['default']
    UChatPrompt: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/ChatPrompt.vue')['default']
    UChatPromptSubmit: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/ChatPromptSubmit.vue')['default']
    UDrawer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputTime: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/InputTime.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_7lrawlpuhkg5ilnnjfv4pxj7nu/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
