ALTER TABLE "action_strategy_snapshots" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "agent_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "answer_deep_evaluations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "capability_jd_signal_embeddings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_artifacts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_commands" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_conversation_summaries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_conversations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_memory_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_run_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "chat_tool_actions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "interview_question_feedback" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "interview_rounds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "interview_session_evaluations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "interview_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "interview_turn_interactions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "interview_turns" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "job_analyses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "job_opportunities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "opportunity_status_history" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "opportunity_terminations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "resume_pdf_import_tasks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "resume_versions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "resumes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "review_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_feedback" ENABLE ROW LEVEL SECURITY;